import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from '@/components/ui/tooltip';
import { HelpCircle } from 'lucide-react';
import { OptimizationResults, MarginSettings, ROASData } from './ROASOptimizer';

interface MetricsDisplayProps {
  results: OptimizationResults;
  marginSettings: MarginSettings;
  currentSpend: number;
  data: ROASData[];
}

interface MetricCardProps {
  label: string;
  value: string;
  className?: string;
  tooltip?: string;
}

const MetricCard = ({ label, value, className = '', tooltip }: MetricCardProps) => (
  <div className="metric-card space-y-1">
    <div className="metric-label flex items-center gap-1">
      {label}
      {tooltip && (
        <TooltipProvider>
          <Tooltip>
            <TooltipTrigger asChild>
              <HelpCircle className="h-3 w-3 text-muted-foreground cursor-help" />
            </TooltipTrigger>
            <TooltipContent className="max-w-xs">
              <p className="text-sm">{tooltip}</p>
            </TooltipContent>
          </Tooltip>
        </TooltipProvider>
      )}
    </div>
    <div className={`metric-value ${className}`}>{value}</div>
  </div>
);

export const MetricsDisplay = ({ 
  results, 
  marginSettings, 
  currentSpend, 
  data 
}: MetricsDisplayProps) => {
  // Calculate organic share if total_sales available
  const totalSalesSum = data
    .filter(d => d.total_sales != null) // Only exclude null/undefined, include 0
    .reduce((sum, d) => sum + (d.total_sales || 0), 0);
  const adSalesSum = data.reduce((sum, d) => sum + d.ad_sales, 0);
  const organicSales = totalSalesSum - adSalesSum;
  const organicShare = totalSalesSum > 0 
    ? `${((organicSales / totalSalesSum) * 100).toFixed(1)}%`
    : '—';

  const deltaSpend = results.deltaSpend || 0;
  const liftVsCurrent = results.liftVsCurrent || 0;

  return (
    <Card className="card-enhanced">
      <CardHeader className="pb-4">
        <CardTitle className="text-lg flex items-center gap-2">
          📊 Optimization Results
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div className="grid grid-cols-6 gap-4">
          <MetricCard
            label="Contribution Margin"
            value={`${marginSettings.contributionMargin.toFixed(1)}%`}
            tooltip="Gross Margin minus Required Net Margin. This is the percentage of revenue available to cover ad spend while maintaining profitability."
          />
          
          <MetricCard
            label="Required mROAS"
            value={`${marginSettings.requiredMROAS.toFixed(2)}x`}
            tooltip="Minimum marginal Return on Ad Spend needed to meet profitability targets. Calculated as 1 ÷ Contribution Margin."
          />
          
          <MetricCard
            label="Organic Share (hist.)"
            value={organicShare}
            tooltip="Historical percentage of total sales that came from organic (non-advertising) sources. Helps understand the full impact of advertising."
          />
          
          <MetricCard
            label="Optimal Daily Spend"
            value={`$${Math.round(results.optimalSpend).toLocaleString()}`}
            className="status-positive"
            tooltip="Recommended daily ad spend that maximizes profitability while meeting the required mROAS threshold."
          />
          
          <MetricCard
            label="Expected Ad Sales @ Opt"
            value={`$${Math.round(results.expectedRevenue).toLocaleString()}`}
            tooltip="Predicted daily ad-attributed sales at the optimal spend level, based on the saturation curve model."
          />
          
          <MetricCard
            label="Total ROAS @ Opt"
            value={`${results.totalRoas.toFixed(2)}x`}
            tooltip="Overall Return on Ad Spend at optimal spend level. Calculated as Expected Ad Sales ÷ Optimal Spend."
          />

          {currentSpend > 0 && (
            <>
              <MetricCard
                label="mROAS @ Opt"
                value={`${results.mRoas.toFixed(2)}x`}
                tooltip="Marginal Return on Ad Spend at the optimal spend level. This is the incremental revenue generated by the last dollar spent."
              />
              
              <MetricCard
                label="Current Spend"
                value={`$${Math.round(currentSpend).toLocaleString()}`}
                tooltip="Your current daily advertising spend level, used as a baseline for comparison with the optimal recommendation."
              />
              
              <MetricCard
                label="Current mROAS"
                value={`${(results.currentMROAS || 0).toFixed(2)}x`}
                className={
                  (results.currentMROAS || 0) >= marginSettings.requiredMROAS 
                    ? 'status-positive' 
                    : 'status-negative'
                }
                tooltip="Your current marginal Return on Ad Spend. Green if above required threshold, red if below. This shows if your current spend is profitable."
              />
              
              <MetricCard
                label="Δ Spend → Opt"
                value={`${deltaSpend >= 0 ? '+' : ''}$${Math.round(deltaSpend).toLocaleString()}`}
                className={deltaSpend >= 0 ? 'status-positive' : 'status-negative'}
                tooltip="The change in daily spend needed to reach optimal level. Positive means increase, negative means decrease."
              />
              
              <MetricCard
                label="Ad-sales Lift vs Current"
                value={`$${Math.round(liftVsCurrent).toLocaleString()}`}
                className="status-positive"
                tooltip="Expected increase in daily ad-attributed sales when moving from current spend to optimal spend level."
              />

              <MetricCard
                label="Feasible"
                value={results.feasible ? 'Yes' : 'No'}
                className={results.feasible ? 'status-positive' : 'status-negative'}
                tooltip="Whether it's possible to achieve the required mROAS threshold within the search bounds. 'No' means you may need to pause or reduce spend significantly."
              />
            </>
          )}
        </div>
      </CardContent>
    </Card>
  );
};